my_finances/urls.py
from django.urls import path
from . import views


app_name = 'my_finances'


urlpatterns = [
    path('income_list/', views.IncomeListView.as_view(), name='income_list'),
    path('income_detail/<pk>', views.IncomeDetailView.as_view(), name='income_detail'),
    path('income_create/', views.IncomeCreateView.as_view(), name='income_create'),
    path('income_update/<pk>', views.IncomeUpdateView.as_view(), name='income_update'),
    path('income_delete/<pk>', views.IncomeDeleteView.as_view(), name='income_delete'),
]

personal_finances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls', namespace='website'), name='website'),
    path('my_finances/', include('my_finances.urls', namespace='my_finances'), name='my_finances'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views


app_name = 'website'


urlpatterns = [
    path('', views.index, name='website_index'),
]

accounts/models.py
from django.db import models

# Create your models here.

my_finances/models.py
from django.db import models


# Create your models here.
class Income(models.Model):
    class IncomeTypes(models.IntegerChoices):
        SALARY = 1, "SALARY"
        BONUS = 2, "BONUS"
        GIFT = 3, "GIFT"
        DIVIDEND = 4, "DIVIDEND"
        OTHER = 5, "OTHER"

    class RepetitionInterval(models.IntegerChoices):
        NA = 1, 'N/A'
        DAY = 2, 'DAY'
        WEEK = 3, 'WEEK'
        MONTH = 4, 'MONTH'
        QUARTER = 5, 'QUARTER'
        SEMESTER = 6, 'SEMESTER'
        YEAR = 7, 'YEAR'

    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    income_type = models.PositiveSmallIntegerField(choices=IncomeTypes.choices)
    recurrent = models.BooleanField(default=False)
    recurrency_interval = models.PositiveSmallIntegerField(choices=RepetitionInterval.choices, default=1)
    recurrency_time = models.PositiveSmallIntegerField(default=0)
    comment = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Income {self.id} - {self.income_type} - {self.date.strftime("%d/%m/%Y")}'
    
    class Meta:
        verbose_name_plural = 'incomes'


class Outcome(models.Model):
    class OutcomeTypes(models.IntegerChoices):
        RENT = 1, 'RENT'
        BILLS = 2, 'BILLS'
        CAR = 3, 'CAR'
        TRAVEL = 4, 'TRAVEL'
        HEALTH = 5, 'HEALTH'
        GROCERIES = 6, 'GROCERIES'
        FUN = 7, 'FUN'
        CLOTHES = 8, 'CLOTHES'
        CHARITY = 9, 'CHARITY'
        INVESTMENT = 10, 'INVESTMENT'
        EDUCATION = 11, 'EDUCATION'

    class RepetitionInterval(models.IntegerChoices):
        NA = 1, 'N/A'
        DAY = 2, 'DAY'
        WEEK = 3, 'WEEK'
        MONTH = 4, 'MONTH'
        QUARTER = 5, 'QUARTER'
        SEMESTER = 6, 'SEMESTER'
        YEAR = 7, 'YEAR'

    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    outcome_type = models.PositiveSmallIntegerField(choices=OutcomeTypes.choices)
    recurrent = models.BooleanField(default=False)
    recurrency_interval = models.PositiveSmallIntegerField(choices=RepetitionInterval.choices, default=1)
    recurrency_time = models.PositiveSmallIntegerField(default=0)
    comment = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Outcome {self.id} - {self.outcome_type} - {self.date.strftime("%d/%m/%Y")}'
    
    class Meta:
        verbose_name_plural = 'outcomes'


class Balance(models.Model):
    class BalanceTypes(models.IntegerChoices):
        CURRENT = 1, 'CURRENT'
        SAVINGS = 2, 'SAVINGS'

    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    balance_type = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'Balance {self.id} - {self.balance_type}'
    
    class Meta:
        verbose_name_plural = 'balances'

website/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class MyApp(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(default='', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='my_apps')

    def __str__(self) -> str:
        return f"MyApp {self.id} {self.name}"
    
    class Meta:
        verbose_name_plural = 'my_apps'
        ordering = ['name']

my_finances/forms.py
from datetime import date
from django import forms
from .models import Income


class DateInput(forms.DateInput):
    input_type = 'date'


class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['value', 'date', 'income_type', 'recurrent', 'recurrency_interval',  'recurrency_time', 'comment']

    value = forms.DecimalField()
    date = forms.DateField(widget=DateInput, initial=date.today())
    income_type = forms.ChoiceField(choices=Income.IncomeTypes.choices)
    recurrent = forms.BooleanField(required=False)
    recurrency_interval = forms.ChoiceField(choices=Income.RepetitionInterval.choices, initial=1)
    recurrency_time = forms.IntegerField(initial=0)
    comment = forms.CharField(max_length=255, required=False, widget=forms.Textarea)
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

accounts/views.py
from django.shortcuts import render

# Create your views here.

my_finances/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from .models import Income
from .forms import IncomeForm


# Create your views here.
class IncomeListView(ListView):
    model = Income
    paginate_by = 100
    # template_name = 'my_finances/income_list.html'
    # queryset = Income.objects.all()
    # context_object_name = 'income_list'


class IncomeDetailView(DetailView):
    model = Income


class IncomeCreateView(CreateView):
    model = Income
    form_class = IncomeForm

    def get_success_url(self) -> str:
        messages.success(self.request, 'Income created successfully!')
        return reverse_lazy('my_finances:income_list')


class IncomeUpdateView(UpdateView):
    model = Income
    form_class = IncomeForm
    
    def get_success_url(self) -> str:
        messages.success(self.request, 'Income updated successfully!')
        return reverse('my_finances:income_detail', kwargs={'pk': self.object.pk})


class IncomeDeleteView(DeleteView):
    model = Income
    
    def get_success_url(self) -> str:
        messages.success(self.request, 'Income deleted successfully!')
        return reverse_lazy('my_finances:income_list')

website/views.py
from django.shortcuts import render
from website.models import MyApp

# Create your views here.
def index(request):
    all_apps = MyApp.objects.all()
    context = {'my_apps': all_apps}
    return render(request, 'website/index.html', context)

templates/my_finances/income_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-8 mx-auto">
        <form method="post">{% csrf_token %}
            <p>Are sure you wnat to delete "{{ income }}"</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
</div>

{% endblock content %}

templates/my_finances/income_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-8 mx-auto">
        {% comment %} {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %} {% endcomment %}

        <h1>Income {{ income.pk }} </h1>
        <ul>
            <li>Date: {{ income.date|date }}</li>
            <li>Type: {{ income.get_income_type_display }}</li>
            <li>Value: ${{ income.value }}</li>
            <li>Repetitive: {{ income.recurrent }}</li>
            {% if income.recurrent %}
                <li>Every: {{ income.recurrency_time }} {{ income.get_recurrency_interval_display }}</li> 
            {% endif %}
        </ul>
        <a href="{% url 'my_finances:income_update' object.pk %}">Update</a>
        <a href="{% url 'my_finances:income_delete' object.pk %}">Delete</a>
    </div>
</div>   

{% endblock content %}

templates/my_finances/income_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-lg-8 mx-auto">
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock content %}

templates/my_finances/income_list.html
{% extends 'base.html' %}

{% block content %}

    {% comment %} {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} {% endcomment %}

    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1>Incomes</h1>
            <ul>
                {% for income in object_list %}
                    <li>
                        <a href="{% url 'my_finances:income_detail' income.pk %}">
                            {{ income.date|date }} - {{ income.get_income_type_display }} - ${{ income.value }} - Repetitive: {{ income.recurrent }}
                            {% if income.recurrent %}
                                every {{ income.recurrency_time }} {{ income.get_recurrency_interval_display }}
                            {% endif %}
                        </a>
                    </li>
                
                {% empty %}
                    <li>No incomes yet</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    

{% endblock content %}